-- SQLite
CREATE TABLE babies (
babyID INTEGER PRIMARY KEY AUTOINCREMENT,
eventType TEXT DEFAULT "Baby" NOT NULL,
birthDate TEXT NOT NULL, -- YYYY-MM-DD
firstName TEXT NOT NULL,
lastName TEXT NOT NULL);